# This is a basic workflow to help you get started with Actions

name: CI

env:
  WF_APPLICATION_ID: 5831c8da-3497-439c-9f4e-e33e7c5fc31b
  WF_TENANT_ID: 4a5378f9-29f4-4d3e-be89-669d03ada9d8

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true
        
      - name: Connection Test
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: 'https://org8858af45.crm11.dynamics.com'
          app-id: '5831c8da-3497-439c-9f4e-e33e7c5fc31b'
          tenant-id: '4a5378f9-29f4-4d3e-be89-669d03ada9d8'
          client-secret: ${{secrets.CLIENT_SECRET_GITHUB_ACTIONS}}

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: 'https://org8858af45.crm11.dynamics.com'
          app-id: ${{env.WF_APPLICATION_ID}}
          tenant-id: ${{env.WF_TENANT_ID}}
          client-secret: ${{secrets.CLIENT_SECRET_GITHUB_ACTIONS}}
          solution-name: aSolution
          solution-output-file: 'aSolution.zip'
          working-directory: 'out'
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
